package control

import (
	"context"
	"errors"
	"time"
)

// GuestReconnectScope is host-authenticated authority, never a guest request.
// The store must lock and compare BOTH current placement and runner connection
// generation, including connected/lifecycle state, throughout each mutation.
// Hosted adapters additionally hold current membership/policy authorization.
type GuestReconnectScope struct {
	WorkspaceID          WorkspaceID
	PoolID               PoolID
	SessionID            SessionID
	RunnerID             RunnerID
	PlacementGeneration  uint64
	ConnectionGeneration uint64
}

// GuestReconnectIdentity is enrolled only by spending a fresh boot capability.
// It contains the public verification key, never guest private key material.
type GuestReconnectIdentity struct {
	BootEpoch string
	PublicKey string
}

// GuestReconnectAttempt is generated by the control plane, not by a runner or
// guest. One pending attempt per session bounds storage. Beginning another
// attempt replaces only the pending challenge, never the active connection or
// bootstrap capability. ExpiresAt is no more than five seconds after issuance.
type GuestReconnectAttempt struct {
	ID        string
	Challenge string
	ExpiresAt time.Time
}

var (
	ErrReconnectInvalid = errors.New("control: invalid guest reconnect")
	ErrReconnectFenced  = errors.New("control: guest reconnect fenced")
	ErrReconnectExpired = errors.New("control: guest reconnect expired")
)

// GuestReconnectStore is an optional persistence port. It does not enable a
// driver capability. Cryptographic proof validation belongs above this port;
// Consume must compare the EXACT identity and attempt that were verified.
// All failures leave bootstrap capabilities and connection epochs unchanged.
// Errors must not contain tokens, keys, challenges or untrusted payloads.
type GuestReconnectStore interface {
	// EnrollGuest spends hash and pins identity in one atomic operation. An
	// existing enrollment cannot be replaced. Ordinary PutSessionBootstrap
	// invalidates enrollment for a new boot; reconnect consumption preserves it.
	EnrollGuest(context.Context, GuestReconnectScope, string, GuestReconnectIdentity, time.Time) error
	// BeginGuestReconnect returns the pinned identity and stores attempt under
	// this exact scope. No enrollment means refusal, never legacy fallback.
	BeginGuestReconnect(context.Context, GuestReconnectScope, GuestReconnectAttempt, time.Time) (GuestReconnectIdentity, error)
	// ReadGuestReconnect reads only the named pending attempt for proof
	// verification. This preliminary read does not authorize the connection or
	// guarantee current runner/lifecycle authority; Consume rechecks every field
	// under a transaction before granting a token or connection epoch.
	ReadGuestReconnect(context.Context, GuestReconnectScope, string) (GuestReconnectIdentity, GuestReconnectAttempt, error)
	// ConsumeGuestReconnect is a single-use compare-and-swap after proof
	// verification. It increments and returns a connection epoch and replaces
	// the bootstrap hash atomically. No retry returns a cached success/token.
	// Delivery and old-relay fencing must still enforce the returned epoch.
	ConsumeGuestReconnect(context.Context, GuestReconnectScope, GuestReconnectIdentity, GuestReconnectAttempt, SessionBootstrap, time.Time) (uint64, error)
}
